AWSTemplateFormatVersion: 2010-09-09
Resources:
    Function:
        Type: AWS::Lambda::Function
        DependsOn: Role
        Properties:
            Runtime: python2.7
            Code: lambda.zip
            Handler: lambda.handler
            Timeout: 15
            Role: !GetAtt Role.Arn

    Role:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    Effect: Allow
                    Principal:
                        Service: lambda.amazonaws.com
                    Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

    Policy:
        Type: AWS::IAM::ManagedPolicy
        DependsOn: Role
        Properties:
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    Effect: Allow
                    Action:
                        - cognito-idp:CreateUserPool
                        - cognito-idp:DeleteUserPool
                        - cognito-idp:UpdateUserPool
                    Resource: '*'
            Roles:
                - !Ref Role

Outputs:
    FunctionArn:
        Value: !GetAtt Function.Arn
        Export:
            Name: CUSTOM-Cognito-User-Pool
