STACK_NAME       := CUSTOM-Cognito-User-Pool
TEMPLATE         := ../TEMPLATE-LAMBDA/cloudformation.yaml ../TEMPLATE-LAMBDA/lambda.yaml
DATA_YAML        := data.yaml
LAMBDA_FUNCTIONS := lambda
include ../misc/Cloudformation.mk
