STACK_NAME       := LAMBDA-Check-Tor-Version
TEMPLATE         := ../TEMPLATE-LAMBDA/cloudformation.yaml ../TEMPLATE-LAMBDA/lambda.yaml
DATA_YAML        := data.yaml
LAMBDA_FUNCTIONS := lambda
include ../misc/Cloudformation.mk
