STACK_NAME       := LAMBDA-Check-Tor-Version
TEMPLATE         := ../TEMPLATE-LAMBDA-Publish-SNS/cloudformation.yaml
DATA_JSON        := data.json
LAMBDA_FUNCTIONS := lambda
include ../misc/Cloudformation.mk
