AWSTemplateFormatVersion: 2010-09-09

Resources:
    #
    ## Lambda Functions
    #
    {{- range $k, $v := .Lambdas }}
    {{- template "lambda.yaml" dictInterfaceToInterface $v "DefaultName" $k }}
    {{- end }}

    #
    ## Rest API
    #
    {{- template "api.yaml" .Api }}

    #
    ## Cognito User Pool & User Pool Client
    #
    CognitoUserPool:
        Type: AWS::CloudFormation::CustomResource
        Properties:
            ServiceToken: {{ .ServiceToken_CognitoUserPool }}
            Properties:
                PoolName: {{ .CognitoUserPoolName }}
                Policies:
                    PasswordPolicy:
                        MinimumLength: 6
                        RequireUppercase: false
                        RequireLowercase: false
                        RequireNumbers: false
                        RequireSymbols: false
                AutoVerifiedAttributes: [email]
                AliasAttributes: [email]
                Schema:
                    - Name: email
                      AttributeDataType: String
                      DeveloperOnlyAttribute: false
                      Mutable: true
                      Required: true
                      StringAttributeConstraints:
                          MinLength: 3

    CognitoUserPoolClient:
        Type: AWS::CloudFormation::CustomResource
        DependsOn: CognitoUserPool
        Properties:
            ServiceToken: {{ .ServiceToken_CognitoUserPoolClient }}
            Properties:
                UserPoolId: !Ref CognitoUserPool
                ClientName: Client
                ReadAttributes:
                    - email
                    - email_verified

    #
    ## DynamoDB Users Table
    #
    DynamoTableUsers:
        Type: AWS::DynamoDB::Table
        Properties:
            ProvisionedThroughput:
                ReadCapacityUnits: 3
                WriteCapacityUnits: 3
            KeySchema:
                - AttributeName: Id
                  KeyType: HASH
                - AttributeName: Email
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: Id
                  AttributeType: S
                - AttributeName: Email
                  AttributeType: S

Outputs:
    ApiUrl:
        Value: {{ template "api.yaml" dictInterfaceToInterface .Api "PrintApiUrl" true }}
    CognitoUserPoolId:
        Value: !Ref CognitoUserPool
    CognitoUserPoolClientId:
        Value: !Ref CognitoUserPoolClient
    CLI:
        Value: !Sub 'make run USER_POOL_ID=${CognitoUserPool} CLIENT_ID=${CognitoUserPoolClient} PASSWORD=test1234 EMAIL=YOUR-EMAIL'
