STACK_NAME       := API-COGNITO
TEMPLATE         := cloudformation.yaml ../TEMPLATE-LAMBDA/lambda.yaml
DATA_YAML        := data.yaml
LAMBDA_DIR       := lambda
LAMBDA_FUNCTIONS := Cognito.PostConfirmation index
include ../misc/Cloudformation.mk
