AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
    Function:
        Type: AWS::Serverless::Function
        DependsOn: Role
        Properties:
            Runtime: python2.7
            CodeUri: lambda.zip
            Handler: lambda.handler
            Timeout: 10
            Role: {{ .LambdaRole }}
            Environment:
                Variables:
                    VERSION: '{{ .GolangVersion }}'
                    TOPIC: {{ .Topic }}
{{- with .Schedules }}
            Events:
{{- range $i, $e := . }}
                Schedule{{ $i }}:
                    Type: Schedule
                    Properties:
                        Schedule: {{ $e }}
{{- end }}{{ end }}
