AWSTemplateFormatVersion: 2010-09-09

Resources:

{{- range $_, $e := .Lambdas }}
{{- template "lambda.yaml" $e }}
{{- end }}

{{- template "api.yaml" .Api }}

Outputs:
    ApiUrl:
        Value: {{ template "api.yaml" dictInterfaceToInterface .Api "PrintApiUrl" true }}
{{- range $k, $v := .Outputs }}
    {{ $k }}:
        Value: {{ $v.Value }}
{{- with $v.ExportName }}
        Export:
            Name: {{ . }}
{{- end }}{{ end }}
