AWSTemplateFormatVersion: 2010-09-09

Resources:

{{- template "lambda.yaml" . }}

{{- with .Outputs }}
Outputs:
{{- range $k, $v := . }}
    {{ $k }}:
        Value: {{ $v.Value }}
{{- with $v.ExportName }}
        Export:
            Name: {{ . }}
{{- end }}{{ end }}{{ end }}
