AWSTemplateFormatVersion: 2010-09-09

Resources:
    Topic:
        Type: AWS::SNS::Topic

{{- range $i, $e := .Subscriptions }}

    Subscription{{ $i }}:
        Type: AWS::SNS::Subscription
        DependsOn: Topic
        Properties:
            TopicArn: !Ref Topic
            Protocol: '{{ index $e 0 }}'
            Endpoint: '{{ index $e 1 }}'
{{- end }}

Outputs:
    TopicARN:
        Value: !Ref Topic
        Export:
            Name: !Sub '${AWS::StackName}'
