AWSTemplateFormatVersion: 2010-09-09

Resources:

    {{- template "lambda.yaml" dictInterfaceToInterface .Lambda.HelloWorld "Include" true }}

    {{- template "lambda.yaml" dictInterfaceToInterface .Lambda.ByeWorld "Include" true }}

    StateMachine:
        Type: AWS::StepFunctions::StateMachine
        DependsOn: Role
        Properties:
            RoleArn: !GetAtt Role.Arn
            DefinitionString: !Sub |-
                {
                    "StartAt": "HelloWorld",
                    "States": {
                        "HelloWorld": {
                            "Type": "Task",
                            "Resource": "${FunctionHelloWorld.Arn}",
                            "Next": "ByeWorld"
                        },
                        "ByeWorld": {
                            "Type": "Task",
                            "Resource": "${FunctionByeWorld.Arn}",
                            "End": true
                        }
                    }
                }

    Role:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    Effect: Allow
                    Principal:
                        Service: !Sub 'states.${AWS::Region}.amazonaws.com'
                    Action: sts:AssumeRole

    Policy:
        Type: AWS::IAM::Policy
        DependsOn: Role
        Properties:
            PolicyName: Default
            Roles: [!Ref Role]
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action: lambda:InvokeFunction
                      Resource:
                          - !GetAtt FunctionHelloWorld.Arn
                          - !GetAtt FunctionByeWorld.Arn
