STACK_NAME       := STEPFUNCTIONS-Example
TEMPLATE         := cloudformation.yaml ../TEMPLATE-LAMBDA/lambda.yaml
DATA_YAML        := data.yaml
LAMBDA_DIR       := lambda
LAMBDA_FUNCTIONS := helloworld byeworld
include ../misc/Cloudformation.mk
