STACK_NAME       := API
TEMPLATE         := ../TEMPLATE-API/cloudformation.yaml ../TEMPLATE-API/api.yaml ../TEMPLATE-LAMBDA/lambda.yaml
DATA_YAML        := data.yaml
LAMBDA_FUNCTIONS := lambda
include ../misc/Cloudformation.mk
